// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1UOmMNlFNE_uSB_3sg87SwlMXRgjIE4I',
    appId: '1:532635501879:android:af8c688a457990c16706b2',
    messagingSenderId: '532635501879',
    projectId: 'wechat-92629',
    storageBucket: 'wechat-92629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYj8duaYhFb2cMaYbEjFvmX2ttK1pTiQ0',
    appId: '1:532635501879:ios:672a02a621e568406706b2',
    messagingSenderId: '532635501879',
    projectId: 'wechat-92629',
    storageBucket: 'wechat-92629.appspot.com',
    androidClientId: '532635501879-vb32367lomrl5blpou9u0rhu77t1v3mp.apps.googleusercontent.com',
    iosClientId: '532635501879-s377anl6for7t5koampi7qeajutnt60r.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
